# Generated by Django 3.2.25 on 2025-06-21 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20250621_2210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
