# Generated by Django 3.2.25 on 2025-06-21 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_auto_20250621_2210'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Post',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=60)),
                        ('created_date', models.DateTimeField(auto_now=True, verbose_name='Date created')),
                        ('description', models.CharField(max_length=150)),
                        ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='accounts.profile', verbose_name='Автор поста')),
                        ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_posts', to='accounts.profile', verbose_name='Получатель поста')),
                    ],
                ),
            ],
            database_operations=[],
        )
    ]
